set windows-shell := ["pwsh.exe", "-c"]

default:
    just --list

prep:
    bash scripts/install.sh

test:
    aya haskeller-tutorial.aya
    aya prover-tutorial.aya

doc:
    mkdir -p dist
    -aya literate.aya.md --pretty-format=html --pretty-color=emacs --pretty-inline-code-style -o dist/literate.aya.html
    # -aya literate.aya.md --pretty-format=markdown --pretty-color=emacs -pretty-inline-code-style -o dist/literate.aya.md