name: Lean 3 Playground

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "lean3"
  lean3:
    name: Lean 3 Examples
    runs-on: ubuntu-latest
    steps:
      - name: install elan
        run: |
          set -o pipefail
          curl -sSfL https://github.com/leanprover/elan/releases/download/v1.3.1/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./elan-init -y --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
      - uses: actions/checkout@v2
      - name: install mathlibtools
        run: |
          pip3 install mathlibtools
      - name: preparation
        run: |
          cd lean3
          leanpkg configure
          leanproject get-mathlib-cache
      - name: build
        run: |
          cd lean3
          bash check_all.sh
