name: Aya CI

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/aya.yml'
      - 'aya/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-aya-examples:
    name: Test Aya Examples
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Cache github-pages
        uses: actions/cache@v4
        with:
            path: github-pages
            key: github-pages
      - uses: extractions/setup-just@v1
        with:
          just-version: 1.35.0
      - name: Setup Aya
        uses: aya-prover/setup-aya@latest
        with:
          version: 'nightly-build'
          distribution: 'jlink'
          build-from-source: 'false'
    #   - name: Show aya version
    #     run: aya --version
    #   - name: Show aya-lsp version
    #     run: aya-lsp --version
    #   - name: Show aya help
    #     run: aya --help
    #   - name: Show aya-lsp help
    #     run: aya-lsp --help

      - name: Typechecking examples
        run: |
            cd aya
            just test
      - name: Generate documentation
        if: >-
          matrix.os == 'ubuntu-latest'
        run: |
            cd aya
            just doc
            cd ..
            mkdir -p github-pages
            mv ./aya/dist ./github-pages/aya
