# based on https://github.com/actions/starter-workflows/blob/main/pages/static.yml
# and https://stackoverflow.com/questions/62750603/github-actions-trigger-another-action-after-one-action-is-completed/65698892#65698892
name: Deploy Gitub Pages

on:
  workflow_run:
    workflows: ["Aya CI"] #, "Lean 4 CI"]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  actions: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
        - name: Download GitHub Pages artifact
          uses: actions/download-artifact@v4
          with:
            name: github-pages
            path: github-pages
            github-token: ${{ secrets.GITHUB_TOKEN }}
            run-id: ${{ github.event.workflow_run.id }}
        - name: Display structure of downloaded files
          run: ls -R
    #   - name: Deploy to GitHub Pages
    #     id: deployment
    #     # Github Pages deployment is enabled conditionally
    #     if: ${{ github.event.workflow_run.conclusion == 'success' }}
    #     uses: actions/deploy-pages@v4