name: Lean 4 Playground

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # This workflow contains a single job called "lean4"
  lean4:
    name: Lean 4 Examples
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    steps:
      - name: install elan on Ubuntu and macOS
        if: matrix.os != 'windows-latest'
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | bash -s -- -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
      - name: install elan on Windows
        if: matrix.os == 'windows-latest'
        run: |
          curl -O --location https://raw.githubusercontent.com/leanprover/elan/master/elan-init.ps1
          powershell -ExecutionPolicy Bypass -f elan-init.ps1 -NoPrompt:$True
          del elan-init.ps1
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.6.1
        with:
          python-version: 3.x
      - name: check on Ubuntu and macOS
        if: matrix.os != 'windows-latest'
        run: |
          cd lean4
          ./install_deps.sh
          ./build.sh
          ./annotate_all.sh
          lake script run check_examples
          lake env leanInk analyze examples/Help.lean
      - name: check on Windows
        if: matrix.os == 'windows-latest'
        run: |
          cd lean4
          lake exe cache get
          lake build
          lake script run check_examples
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./lean4/dist

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: lean4
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
