name: TLA+ CI

on:
  push:
    branches: [ main ]
    paths:
      - 'tla/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tla:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: extractions/setup-just@v1
        with:
          just-version: 1.35.0
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
      - name: Cache tla2tools.jar
        uses: actions/cache@v4
        with:
            path: tla/.tla
            key: ${{ runner.os }}-tla
      - name: check
        run: |
            cd tla
            just prep-tla
            just check pluscal.tla

